
### Get all accounts

GET http://localhost:9000/accounts HTTP/1.1
Accept: application/json



### Get An Account

GET http://localhost:9000/accounts/ddfd-4d16-4976-b074-23fef65053aa HTTP/1.1
Accept: application/json



### Add An Account

POST http://localhost:9000/accounts HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "Kim Schmidt"
}

### Get an account's balance

GET http://localhost:9000/accounts/826ee966-32d4-4b09-b7c1-3ef1a20a17b6/balance HTTP/1.1